defaults: &defaults
  dalli: false
  debug: false
  logging: true
  serve_static: false
  sprockets:
    assets_prefix: '/assets'
    assets_paths:
      - stylesheets
      - javascripts
      - images
      - fonts

development:
  <<: *defaults
  debug: true

test:
  <<: *defaults

production:
  <<: *defaults
