defaults: &defaults
  dalli: false
  debug: false
  logging: true
  serve_static: false
  google_analytics: UA-XXX-XXX
  notifications:
    sender: service@example.com
    recipients: 
      - you@example.com
      - me@example.com
      - him@example.com
  compass:
    images:   images
    fonts:    fonts
  sprockets:
    digest:   true
    assets_prefix: /assets
    paths:
      js:     javascripts
      css:    stylesheets
      static:
        - images
        - fonts

development:
  <<: *defaults
  debug: true

test:
  <<: *defaults

production:
  <<: *defaults
